export const THRUST_TO_SUB_PROGRAM: Record<string, string> = {
    "Asset Preservation - Construction / Upgrading / Rehabilitation of Drainage along National Roads - Primary Roads": "1",
    "Asset Preservation - Construction / Upgrading / Rehabilitation of Drainage along National Roads - Secondary Roads": "1",
    "Asset Preservation - Construction / Upgrading / Rehabilitation of Drainage along National Roads - Tertiary Roads": "1",
    "Asset Preservation - Preventive Maintenance - Primary Roads": "2",
    "Asset Preservation - Preventive Maintenance - Secondary Roads": "2",
    "Asset Preservation - Preventive Maintenance - Tertiary Roads": "2",
    "Asset Preservation - Rehabilitation/ Reconstruction of Roads with Slips, Slope Collapse, and Landslide - Primary Roads": "3",
    "Asset Preservation - Rehabilitation/ Reconstruction of Roads with Slips, Slope Collapse, and Landslide - Secondary Roads": "3",
    "Asset Preservation - Rehabilitation/ Reconstruction of Roads with Slips, Slope Collapse, and Landslide - Tertiary Roads": "3",
    "Asset Preservation - Rehabilitation/ Reconstruction/ Upgrading of Damaged Paved Roads - Primary Roads": "4",
    "Asset Preservation - Rehabilitation/ Reconstruction/ Upgrading of Damaged Paved Roads - Secondary Roads": "4",
    "Asset Preservation - Rehabilitation/ Reconstruction/ Upgrading of Damaged Paved Roads - Tertiary Roads": "4",
    "Network Development - Road Widening - Primary Roads": "5",
    "Network Development - Road Widening - Secondary Roads": "5",
    "Network Development - Road Widening - Tertiary Roads": "5",
    "Network Development - Paving of Unpaved Roads - Primary Roads": "6",
    "Network Development - Paving of Unpaved Roads - Secondary Roads": "6",
    "Network Development - Paving of Unpaved Roads - Tertiary Roads": "6",
    "Network Development - Off-Carriageway Improvement - Primary Roads": "7",
    "Network Development - Off-Carriageway Improvement - Secondary Roads": "7",
    "Network Development - Off-Carriageway Improvement - Tertiary Roads": "7",
    "Network Development - Construction of By-Pass and Diversion Roads": "8",
    "Network Development - Construction of Flyovers/ Interchanges/ Underpasses/ Long Span Bridges": "9",
    "Network Development - Construction of Missing Links/ New Roads": "10",
    "Bridge - Construction of New Bridges": "11",
    "Bridge - Rehabilitation/ Major Repair of Permanent Bridges": "12",
    "Bridge - Replacement of Bridges (Temporary to Permanent)": "13",
    "Bridge - Replacement of Permanent Weak Bridges": "14",
    "Bridge - Retrofitting/ Strengthening of Permanent Bridges": "15",
    "Bridge - Widening of Permanent Bridges": "16",
    "Construction/ Rehabilitation of Flood Mitigation Facilities within Major River Basins and Principal Rivers": "22",
    "Convergence and Special Support Program - Construction/ Improvement of Access Roads leading to Airports (Kalsada Tungo sa Paliparan, Riles at Daungan Program - KATUPARAN)": "26",
    "Convergence and Special Support Program - Construction/ Improvement of Access Roads leading to Declared Tourism Destinations (Tourism Road Infrastructure Program - TRIP)": "27",
    "Convergence and Special Support Program - Construction/ Improvement of Access Roads leading to Seaports (Kalsada Tungo sa Paliparan, Riles at Daungan Program - KATUPARAN)": "28",
    "Convergence and Special Support Program - Construction/ Improvement of Access Roads leading to Trades, Industries and Economic Zones (Roads Leveraging Linkages for Industry and Trade Infrastructure Program - ROLL-IT)": "29",
    "Convergence and Special Support Program - Construction/Improvement of Various Infrastructures in Support of National Security (Tatag ng Imprastraktura para sa Kapayapaan at Seguridad Program - TIKAS)": "30",
    "Convergence and Special Support Program - Improvement of Capacity of Provincial Bridges along Provincial Roads (Provincial Bridges for Economic Development - PROBRED)": "49",
    "Convergence and Special Support Program - Construction/ Improvement of Access Roads leading to Railway Stations (Kalsada Tungo sa Paliparan, Riles at Daungan Program - KATUPARAN)": "50",
    "Construction/ Maintenance of Flood Mitigation Structures and Drainage Systems": "48",
    "Special Road Fund - Motor Vehicle Users Charge (MVUC) as per R.A. 11239": "118"
};
